package ph.edu.dlsu.lbycpob.animoquest.service;

import org.springframework.stereotype.Service;
import ph.edu.dlsu.lbycpob.animoquest.model.MasterlistCourse;
import ph.edu.dlsu.lbycpob.animoquest.repository.MasterlistCourseRepository;

import java.util.List;

@Service
public class CourseManagementService {
    private final MasterlistCourseRepository masterlistCourseRepository;

    public CourseManagementService(MasterlistCourseRepository masterlistCourseRepository) {
        this.masterlistCourseRepository = masterlistCourseRepository;
    }

    // GETS ALL COURSES
    public List<MasterlistCourse> getAllCourses() {
        return masterlistCourseRepository.findAll();
    }

    // GET COURSE
    public MasterlistCourse getCourse(Long id) {
        if (id == null) {
            throw new IllegalArgumentException("Course ID cannot be null.");
        }

        return masterlistCourseRepository.findById(id).orElseThrow(
                () -> new IllegalArgumentException("Course was not found.")
        );
    }

    // ADD COURSE (ID is auto-generated by DB)
    public MasterlistCourse addCourse(String code, String name, int units, boolean passFail) {
        validateCourse(code, name, units);

        MasterlistCourse course = new MasterlistCourse();
        course.setCode(code.trim().toUpperCase());
        course.setName(name.trim());
        course.setUnits(units);
        course.setPassFail(passFail);

        return masterlistCourseRepository.save(course);
    }

    // UPDATE COURSE
    public MasterlistCourse updateCourse(Long id, String code, String name, int units, boolean passFail) {
        if (id == null) {
            throw new IllegalArgumentException("Course ID cannot be null for updates.");
        }

        validateCourse(code, name, units);

        MasterlistCourse course = getCourse(id);
        course.setCode(code.trim().toUpperCase());
        course.setName(name.trim());
        course.setUnits(units);
        course.setPassFail(passFail);

        return masterlistCourseRepository.save(course);
    }

    // DELETE COURSE
    public void deleteCourse(Long id) {
        MasterlistCourse course = getCourse(id);
        masterlistCourseRepository.delete(course);
    }

    // VALIDATION
    private void validateCourse(String code, String name, int units) {
        if (code == null || code.trim().isEmpty()) {
            throw new IllegalArgumentException("Course code cannot be empty.");
        }
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Course name cannot be empty.");
        }
        if (units < 0) {
            throw new IllegalArgumentException("Course units cannot be negative.");
        }
    }
}